services:
  - type: web
    name: tg-ai-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python tg_openrouter_bot.py
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
