export type ModelType = "Текст" | "Изображения" | "Видео" | "Аудио" | "Код" | "Поиск";

export type ModelCatalogItem = {
  id: string;
  name: string;
  company: string;
  companyShort: string;
  type: ModelType;
  description: string;
  longDescription: string;
  rating: number;
  isFree: boolean;
  tags: string[];
  accentFrom: string;
  accentTo: string;
  heroBadge: string;
  releaseNote: string;
  promptExample: string;
  strengths: string[];
  bestFor: string[];
  pricingHint: string;
  url: string;
  trendScore: number;
  isNew: boolean;
};

export const MODEL_TYPES: ModelType[] = ["Текст", "Изображения", "Видео", "Аудио", "Код", "Поиск"];

export const AI_MODELS: ModelCatalogItem[] = [
  {
    id: "openai-gpt-4-5",
    name: "GPT-4.5",
    company: "OpenAI",
    companyShort: "OA",
    type: "Текст",
    description: "Большая мультимодальная модель для сложных диалогов, стратегии и редактуры.",
    longDescription: "Флагманская линейка OpenAI для глубоких рассуждений, переписывания, исследований и премиального ассистента общего назначения.",
    rating: 4.9,
    isFree: false,
    tags: ["Флагман", "Мультимодальность", "Премиум"],
    accentFrom: "#00F2FF",
    accentTo: "#6E8BFF",
    heroBadge: "Флагман 2026",
    releaseNote: "Сильна в сложных задачах и длинном контексте.",
    promptExample: "Собери стратегию запуска digital-продукта на 90 дней с KPI, бюджетом и рисками.",
    strengths: ["Стратегия", "Редактура", "Исследования"],
    bestFor: ["CEO", "Маркетинг", "Консалтинг"],
    pricingHint: "Платный доступ через API и приложения партнёров.",
    url: "https://openai.com/",
    trendScore: 99,
    isNew: true,
  },
  {
    id: "openai-gpt-4-1",
    name: "GPT-4.1",
    company: "OpenAI",
    companyShort: "OA",
    type: "Код",
    description: "Сильный универсал для кода, автотестов, документации и агентных сценариев.",
    longDescription: "Семейство OpenAI для production-разработки, ревью кода, правок по репозиторию и технических пайплайнов.",
    rating: 4.8,
    isFree: false,
    tags: ["Код", "Агенты", "CI/CD"],
    accentFrom: "#00F2FF",
    accentTo: "#4CC9F0",
    heroBadge: "Dev Stack",
    releaseNote: "Оптимизирована под инженерные сценарии и инструменты.",
    promptExample: "Отрефакторь React-компонент, вынеси состояние в Zustand и добавь тест-кейсы.",
    strengths: ["Код", "Архитектура", "Отладка"],
    bestFor: ["Full-stack", "DevOps", "QA"],
    pricingHint: "Платная модель для интенсивной разработки.",
    url: "https://openai.com/",
    trendScore: 94,
    isNew: false,
  },
  {
    id: "anthropic-claude-opus-4",
    name: "Claude Opus 4",
    company: "Anthropic",
    companyShort: "AN",
    type: "Текст",
    description: "Глубокое аналитическое мышление, сильная работа с длинными документами и RAG.",
    longDescription: "Премиальный Claude для сложных исследовательских задач, договоров, аналитики и аккуратной письменной речи.",
    rating: 4.9,
    isFree: false,
    tags: ["Аналитика", "Длинный контекст", "Документы"],
    accentFrom: "#FF00F5",
    accentTo: "#6E8BFF",
    heroBadge: "Research Grade",
    releaseNote: "Один из сильнейших вариантов для документов и reasoning.",
    promptExample: "Сравни два договора и выдели риски для подрядчика в формате таблицы.",
    strengths: ["Документы", "Аналитика", "Тон ответа"],
    bestFor: ["Юристы", "Аналитики", "PM"],
    pricingHint: "Премиальная подписка и API.",
    url: "https://www.anthropic.com/",
    trendScore: 97,
    isNew: true,
  },
  {
    id: "anthropic-claude-sonnet-4",
    name: "Claude Sonnet 4",
    company: "Anthropic",
    companyShort: "AN",
    type: "Код",
    description: "Баланс скорости и качества для ежедневной разработки, поддержки и бизнес-задач.",
    longDescription: "Практичный Claude для инженерии, product-задач, UI-текстов и рабочих агентов.",
    rating: 4.8,
    isFree: false,
    tags: ["Скорость", "Код", "Рабочий ассистент"],
    accentFrom: "#FF00F5",
    accentTo: "#00F2FF",
    heroBadge: "Balanced Pro",
    releaseNote: "Хорошо держит качество при высокой скорости ответа.",
    promptExample: "Составь ADR для миграции монолита на модульную архитектуру.",
    strengths: ["Код", "Планирование", "Коммуникации"],
    bestFor: ["Разработчики", "Продакты", "Саппорт"],
    pricingHint: "Платный доступ.",
    url: "https://www.anthropic.com/",
    trendScore: 92,
    isNew: true,
  },
  {
    id: "google-gemini-2-5-pro",
    name: "Gemini 2.5 Pro",
    company: "Google",
    companyShort: "GO",
    type: "Текст",
    description: "Топовая модель Google для reasoning, видео-понимания и масштабных контекстов.",
    longDescription: "Флагман Gemini для сложных исследований, анализа мультимодального контента и агентных сценариев в экосистеме Google.",
    rating: 4.8,
    isFree: false,
    tags: ["Reasoning", "Видео", "Мультимодальность"],
    accentFrom: "#6E8BFF",
    accentTo: "#00F2FF",
    heroBadge: "Google Flagship",
    releaseNote: "Усилена в аналитике и мультимодальных задачах.",
    promptExample: "Проанализируй стратегию конкурента по презентации и предложи контратаку.",
    strengths: ["Мультимодальность", "Исследования", "Сценарии"],
    bestFor: ["Маркетинг", "Видео-команды", "Аналитики"],
    pricingHint: "Часть сценариев доступна в подписке, API платный.",
    url: "https://deepmind.google/technologies/gemini/",
    trendScore: 96,
    isNew: true,
  },
  {
    id: "google-gemini-2-5-flash",
    name: "Gemini 2.5 Flash",
    company: "Google",
    companyShort: "GO",
    type: "Текст",
    description: "Быстрая и доступная модель для массовых продуктов, ассистентов и автоворкфлоу.",
    longDescription: "Облегчённый Gemini для приложений с высокой нагрузкой, where latency matters.",
    rating: 4.6,
    isFree: true,
    tags: ["Скорость", "API", "Масштаб"],
    accentFrom: "#6E8BFF",
    accentTo: "#FF00F5",
    heroBadge: "Flash",
    releaseNote: "Подходит для продакшн-нагрузки и быстрых ответов.",
    promptExample: "Суммируй 50 отзывов клиентов в 5 инсайтов и 3 гипотезы для роста.",
    strengths: ["Latency", "Суммаризация", "Потоковые ответы"],
    bestFor: ["Стартапы", "Чат-боты", "API-продукты"],
    pricingHint: "Есть бесплатные квоты в части продуктов Google.",
    url: "https://deepmind.google/technologies/gemini/",
    trendScore: 91,
    isNew: true,
  },
  {
    id: "xai-grok-4",
    name: "Grok 4",
    company: "xAI",
    companyShort: "XA",
    type: "Текст",
    description: "Ставка на живой стиль, актуальность, быстрые дискуссии и энергичный тон.",
    longDescription: "Флагман xAI для разговорных сценариев, мозговых штурмов и широкой экспертизы в потребительских интерфейсах.",
    rating: 4.7,
    isFree: false,
    tags: ["Актуальность", "Диалог", "Быстрый стиль"],
    accentFrom: "#00F2FF",
    accentTo: "#FF00F5",
    heroBadge: "Hot Now",
    releaseNote: "Силен в conversational UX и живых ответах.",
    promptExample: "Собери 10 ярких идей для запуска телеграм-бота с бесплатными ИИ-моделями.",
    strengths: ["Брейншторм", "Тон", "Диалоги"],
    bestFor: ["Креаторы", "СММ", "Комьюнити"],
    pricingHint: "Обычно доступен по подписке и API-партнёрам.",
    url: "https://x.ai/",
    trendScore: 95,
    isNew: true,
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    company: "DeepSeek",
    companyShort: "DS",
    type: "Текст",
    description: "Открытая reasoning-модель для логики, математики и цепочек рассуждений.",
    longDescription: "Популярная модель с сильным reasoning-профилем и большим интересом сообщества к открытым сценариям.",
    rating: 4.7,
    isFree: true,
    tags: ["Open", "Reasoning", "Логика"],
    accentFrom: "#6E8BFF",
    accentTo: "#00F2FF",
    heroBadge: "Open Reasoning",
    releaseNote: "Сильная открытая альтернатива для логических задач.",
    promptExample: "Реши задачу по вероятности пошагово и объясни ход решения.",
    strengths: ["Логика", "Математика", "Открытый стек"],
    bestFor: ["Обучение", "R&D", "Open-source"],
    pricingHint: "Часто доступна бесплатно у провайдеров и в open deployment.",
    url: "https://www.deepseek.com/",
    trendScore: 93,
    isNew: false,
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    company: "DeepSeek",
    companyShort: "DS",
    type: "Код",
    description: "Сильная открытая MoE-модель для диалогов, кода и продакшн-пайплайнов.",
    longDescription: "Практичная open-модель с широкой поддержкой провайдеров, особенно для cost-efficient приложений.",
    rating: 4.6,
    isFree: true,
    tags: ["Open", "MoE", "Код"],
    accentFrom: "#6E8BFF",
    accentTo: "#FF00F5",
    heroBadge: "Open Scale",
    releaseNote: "Часто используют как доступную базу для кастомных решений.",
    promptExample: "Сгенерируй REST API на Next.js 15 с Zod-валидацией и тестами.",
    strengths: ["Код", "Стоимость", "Кастомизация"],
    bestFor: ["Инженеры", "Стартапы", "Self-host"],
    pricingHint: "Можно запускать у ряда провайдеров бесплатно.",
    url: "https://www.deepseek.com/",
    trendScore: 88,
    isNew: false,
  },
  {
    id: "meta-llama-4-maverick",
    name: "Llama 4 Maverick",
    company: "Meta",
    companyShort: "ME",
    type: "Текст",
    description: "Открытая мультимодальная модель Meta для ассистентов и кастомных платформ.",
    longDescription: "Представитель семейства Llama 4 с акцентом на производительность и широкую интеграцию в экосистему open моделей.",
    rating: 4.5,
    isFree: true,
    tags: ["Open", "Meta", "Мультимодальность"],
    accentFrom: "#00F2FF",
    accentTo: "#6E8BFF",
    heroBadge: "Meta Open",
    releaseNote: "Интересен для open deployments и кастомных агентов.",
    promptExample: "Составь карту внедрения AI-помощника в отдел продаж на 12 недель.",
    strengths: ["Open stack", "Гибкость", "Интеграции"],
    bestFor: ["Интеграторы", "Разработчики", "Лаборатории"],
    pricingHint: "Открытая модель, доступна у многих провайдеров.",
    url: "https://ai.meta.com/",
    trendScore: 85,
    isNew: true,
  },
  {
    id: "meta-llama-4-scout",
    name: "Llama 4 Scout",
    company: "Meta",
    companyShort: "ME",
    type: "Текст",
    description: "Более лёгкий вариант Llama 4 для встраиваемых и cost-efficient сценариев.",
    longDescription: "Подходит там, где важны скорость, контроль стека и гибкая стоимость эксплуатации.",
    rating: 4.4,
    isFree: true,
    tags: ["Open", "Лёгкая", "API"],
    accentFrom: "#00F2FF",
    accentTo: "#4CC9F0",
    heroBadge: "Lean Open",
    releaseNote: "Хороший вариант для дешёвых интеграций.",
    promptExample: "Сделай FAQ для сайта сервиса ремонта квартир в 12 вопросах.",
    strengths: ["Быстрота", "Стоимость", "Гибкость"],
    bestFor: ["Малый бизнес", "MVP", "Сервисные боты"],
    pricingHint: "Открытая и доступная у множества поставщиков.",
    url: "https://ai.meta.com/",
    trendScore: 81,
    isNew: true,
  },
  {
    id: "mistral-large-2",
    name: "Mistral Large 2",
    company: "Mistral AI",
    companyShort: "MI",
    type: "Текст",
    description: "Европейский флагман для enterprise, кода, многоязычности и приватных развертываний.",
    longDescription: "Одна из ключевых моделей Mistral для компаний, которым нужны сильные ответы и гибкий deployment.",
    rating: 4.6,
    isFree: false,
    tags: ["Enterprise", "EU", "Многоязычность"],
    accentFrom: "#FF00F5",
    accentTo: "#00F2FF",
    heroBadge: "EU Stack",
    releaseNote: "Часто рассматривается как enterprise-альтернатива американским флагманам.",
    promptExample: "Подготовь multilingual support playbook для e-commerce бренда.",
    strengths: ["Многоязычность", "Enterprise", "Код"],
    bestFor: ["Европейские компании", "B2B", "Compliance"],
    pricingHint: "Платный API и enterprise-условия.",
    url: "https://mistral.ai/",
    trendScore: 84,
    isNew: false,
  },
  {
    id: "black-forest-flux-1-kontext-pro",
    name: "FLUX.1 Kontext Pro",
    company: "Black Forest Labs",
    companyShort: "BF",
    type: "Изображения",
    description: "Премиальная генерация изображений и точное управление стилем/правками.",
    longDescription: "Сильное направление Black Forest Labs для коммерческого дизайна, рекламных визуалов и controllable image generation.",
    rating: 4.8,
    isFree: false,
    tags: ["Image Gen", "Контроль стиля", "Реклама"],
    accentFrom: "#00F2FF",
    accentTo: "#FF00F5",
    heroBadge: "Visual Pro",
    releaseNote: "Один из самых заметных стеков в image generation нового поколения.",
    promptExample: "Создай футуристичный баннер для AI-сервиса в стиле cyberpunk luxury.",
    strengths: ["Качество", "Контроль", "Детализация"],
    bestFor: ["Дизайнеры", "Маркетинг", "Креатив"],
    pricingHint: "Чаще всего платный доступ.",
    url: "https://bfl.ai/",
    trendScore: 94,
    isNew: true,
  },
  {
    id: "midjourney-v7",
    name: "Midjourney V7",
    company: "Midjourney",
    companyShort: "MJ",
    type: "Изображения",
    description: "Культовый генератор картинок с сильной художественной подачей и атмосферой.",
    longDescription: "Выбор креаторов для концепт-арта, рекламных moodboard и визуалов с выраженным стилем.",
    rating: 4.8,
    isFree: false,
    tags: ["Арт", "Креатив", "Детализация"],
    accentFrom: "#FF00F5",
    accentTo: "#6E8BFF",
    heroBadge: "Art Engine",
    releaseNote: "Сильный художественный характер и узнаваемое качество.",
    promptExample: "Нарисуй премиальную витрину каталога ИИ в киберпанк-стиле с неоном и стеклом.",
    strengths: ["Стиль", "Композиция", "Вау-эффект"],
    bestFor: ["Арт-директора", "SMM", "Брендинг"],
    pricingHint: "Подписка через собственный сервис.",
    url: "https://www.midjourney.com/",
    trendScore: 95,
    isNew: true,
  },
  {
    id: "kling-2-0",
    name: "Kling 2.0",
    company: "Kuaishou",
    companyShort: "KL",
    type: "Видео",
    description: "Громкий видеогенератор для кинематографичных сцен, движений камеры и персонажей.",
    longDescription: "Используется для рекламных роликов, тизеров и клипов, когда нужен эффектный motion output.",
    rating: 4.7,
    isFree: false,
    tags: ["Video Gen", "Кино", "Движение камеры"],
    accentFrom: "#00F2FF",
    accentTo: "#6E8BFF",
    heroBadge: "Cinema Motion",
    releaseNote: "Сильный игрок в гонке генеративного видео.",
    promptExample: "Сделай тизер AI-каталога: пролёт камеры по неоновому мегаполису и интерфейсу сервиса.",
    strengths: ["Видео", "Кинематографичность", "Сцены"],
    bestFor: ["Продакшн", "Реклама", "Креаторы"],
    pricingHint: "Ограниченные кредиты и платные тарифы.",
    url: "https://klingai.com/",
    trendScore: 93,
    isNew: true,
  },
  {
    id: "runway-gen-4",
    name: "Runway Gen-4",
    company: "Runway",
    companyShort: "RW",
    type: "Видео",
    description: "Премиальное видео нового поколения для продакшна, рекламы и брендов.",
    longDescription: "Фокус на controllable motion, consistency и рабочие инструменты для creative teams.",
    rating: 4.8,
    isFree: false,
    tags: ["Video Pro", "Brand", "Production"],
    accentFrom: "#FF00F5",
    accentTo: "#00F2FF",
    heroBadge: "Studio Grade",
    releaseNote: "Один из самых сильных коммерческих видеостеков.",
    promptExample: "Создай 15-секундный рекламный ролик AI-платформы с роскошным неоновым UI.",
    strengths: ["Продакшн", "Стабильность кадров", "Workflow"],
    bestFor: ["Агентства", "Видеостудии", "Бренды"],
    pricingHint: "Платные кредиты.",
    url: "https://runwayml.com/",
    trendScore: 97,
    isNew: true,
  },
  {
    id: "luma-dream-machine",
    name: "Luma Dream Machine",
    company: "Luma AI",
    companyShort: "LU",
    type: "Видео",
    description: "Быстрая генерация видео и живых визуальных сцен для социальных сетей и прототипов.",
    longDescription: "Известен скоростью, удобством и дружелюбным входом для креаторов без тяжёлого пайплайна.",
    rating: 4.6,
    isFree: true,
    tags: ["Video Fast", "Соцсети", "Prototype"],
    accentFrom: "#6E8BFF",
    accentTo: "#00F2FF",
    heroBadge: "Fast Motion",
    releaseNote: "Часто выбирают за скорость и доступный вход в видео-AI.",
    promptExample: "Сгенерируй короткую сцену для промо запуска AI-каталога с неоновой типографикой.",
    strengths: ["Скорость", "Простота", "Соцсети"],
    bestFor: ["Контент-мейкеры", "Маркетинг", "MVP-видео"],
    pricingHint: "Есть бесплатные кредиты, затем платные планы.",
    url: "https://lumalabs.ai/dream-machine",
    trendScore: 89,
    isNew: false,
  },
  {
    id: "suno-v4-5",
    name: "Suno v4.5",
    company: "Suno",
    companyShort: "SU",
    type: "Аудио",
    description: "Генерация полноценных песен с вокалом, жанром, атмосферой и продакшн-качеством.",
    longDescription: "Один из главных продуктов для AI-музыки: демо, саундтреки, джинглы и идеи треков.",
    rating: 4.8,
    isFree: true,
    tags: ["Music AI", "Вокал", "Продакшн"],
    accentFrom: "#FF00F5",
    accentTo: "#6E8BFF",
    heroBadge: "Hit Maker",
    releaseNote: "Сильнейший consumer-интерфейс для AI-музыки.",
    promptExample: "Создай энергичный джингл для каталога нейросетей: cyberpunk, premium, futuristic.",
    strengths: ["Песни", "Качество", "Эмоция"],
    bestFor: ["Музыканты", "Маркетинг", "Видео"],
    pricingHint: "Есть бесплатный режим и платные планы.",
    url: "https://suno.com/",
    trendScore: 92,
    isNew: true,
  },
  {
    id: "udio-1-5",
    name: "Udio 1.5",
    company: "Udio",
    companyShort: "UD",
    type: "Аудио",
    description: "AI-музыка с вниманием к структуре композиции, голосу и музыкальному вкусу.",
    longDescription: "Популярная альтернатива Suno для генерации песен, демо и кастомных музыкальных идей.",
    rating: 4.7,
    isFree: true,
    tags: ["Music", "Голос", "Композиция"],
    accentFrom: "#00F2FF",
    accentTo: "#FF00F5",
    heroBadge: "Music Lab",
    releaseNote: "Хорош для музыкальных экспериментов и кастомных треков.",
    promptExample: "Сгенерируй трек-открывашку для сайта AI-каталога в жанре synthwave.",
    strengths: ["Музыка", "Кастомизация", "Вокал"],
    bestFor: ["Музыканты", "Подкастеры", "Бренды"],
    pricingHint: "Есть бесплатный уровень и платные лимиты.",
    url: "https://www.udio.com/",
    trendScore: 87,
    isNew: false,
  },
  {
    id: "elevenlabs-v3",
    name: "ElevenLabs v3",
    company: "ElevenLabs",
    companyShort: "EL",
    type: "Аудио",
    description: "Эталонный voice AI для озвучки, дубляжа, голосовых агентов и студийных роликов.",
    longDescription: "Один из лучших стеков для text-to-speech, voice cloning и продвинутой голосовой персонализации.",
    rating: 4.9,
    isFree: true,
    tags: ["Voice AI", "TTS", "Дубляж"],
    accentFrom: "#6E8BFF",
    accentTo: "#FF00F5",
    heroBadge: "Voice Prime",
    releaseNote: "Ориентир рынка в синтезе речи и голосовых продуктах.",
    promptExample: "Озвучь премиальное приветствие для каталога нейросетей уверенным мужским голосом.",
    strengths: ["Голос", "Качество", "Локализация"],
    bestFor: ["Подкасты", "Видео", "Voice agents"],
    pricingHint: "Есть бесплатный тариф и платные кредиты.",
    url: "https://elevenlabs.io/",
    trendScore: 96,
    isNew: true,
  },
  {
    id: "perplexity-sonar",
    name: "Perplexity Sonar",
    company: "Perplexity",
    companyShort: "PX",
    type: "Поиск",
    description: "Поисковая модель с акцентом на ответы по вебу, источники и актуальные данные.",
    longDescription: "Используется для AI-поиска, актуальных сводок и retrieval-помощников с прозрачной ссылочной базой.",
    rating: 4.6,
    isFree: true,
    tags: ["Поиск", "Веб", "Источники"],
    accentFrom: "#00F2FF",
    accentTo: "#6E8BFF",
    heroBadge: "Live Search",
    releaseNote: "Практичный стек для поиска и верификации информации.",
    promptExample: "Собери краткий рынок-анализ генеративного видео за последние 30 дней.",
    strengths: ["Поиск", "Ссылки", "Актуальность"],
    bestFor: ["Исследования", "Контент", "Аналитика"],
    pricingHint: "Есть бесплатные сценарии и платные API-планы.",
    url: "https://www.perplexity.ai/",
    trendScore: 86,
    isNew: false,
  },
  {
    id: "cursor-tab-models",
    name: "Cursor Tab + Agent",
    company: "Cursor",
    companyShort: "CU",
    type: "Код",
    description: "AI-среда разработки с агентами, автодополнением и редактором под код.",
    longDescription: "Не отдельная модель в классическом смысле, а топовый продуктовый слой над LLM для инженерной работы.",
    rating: 4.7,
    isFree: false,
    tags: ["IDE", "Агенты", "Разработка"],
    accentFrom: "#FF00F5",
    accentTo: "#00F2FF",
    heroBadge: "Dev Workflow",
    releaseNote: "Быстро стал стандартом для AI-assisted coding.",
    promptExample: "Разбей задачу на файлы, напиши код и перечисли команды для проверки.",
    strengths: ["IDE", "Код", "Поток работы"],
    bestFor: ["Разработчики", "Тимлиды", "Стартапы"],
    pricingHint: "Платный продуктовый доступ.",
    url: "https://www.cursor.com/",
    trendScore: 90,
    isNew: false,
  },
  {
    id: "runway-frames",
    name: "Runway Frames",
    company: "Runway",
    companyShort: "RW",
    type: "Изображения",
    description: "Инструмент Runway для создания кадров и стилевых визуалов под video-first пайплайн.",
    longDescription: "Полезен для сторибордов, keyframes и визуальных концепций перед видео-генерацией.",
    rating: 4.5,
    isFree: false,
    tags: ["Frames", "Storyboard", "Video-first"],
    accentFrom: "#6E8BFF",
    accentTo: "#00F2FF",
    heroBadge: "Storyboard",
    releaseNote: "Связывает image- и video-воркфлоу в одном стекe.",
    promptExample: "Сделай keyframe главного экрана AI-каталога как кадр футуристичной рекламы.",
    strengths: ["Кадры", "Препродакшн", "Видео-команды"],
    bestFor: ["Режиссёры", "Продюсеры", "Дизайнеры"],
    pricingHint: "Входит в коммерческий стек Runway.",
    url: "https://runwayml.com/",
    trendScore: 78,
    isNew: true,
  },
  {
    id: "pika-2-2",
    name: "Pika 2.2",
    company: "Pika",
    companyShort: "PK",
    type: "Видео",
    description: "Лёгкий и быстрый генератор роликов для соцсетей, рекламоносителей и short-form контента.",
    longDescription: "Удобен, когда нужен быстрый заход в генеративное видео без тяжёлого production-стека.",
    rating: 4.4,
    isFree: true,
    tags: ["Shorts", "Соцсети", "Быстро"],
    accentFrom: "#FF00F5",
    accentTo: "#00F2FF",
    heroBadge: "Social Video",
    releaseNote: "Популярен в маркетинговых и creator-сценариях.",
    promptExample: "Сделай вертикальный 10-секундный тизер нового AI-сайта для Reels.",
    strengths: ["Скорость", "Клипы", "Удобство"],
    bestFor: ["SMM", "Блогеры", "Перформанс-команды"],
    pricingHint: "Есть бесплатные кредиты.",
    url: "https://pika.art/",
    trendScore: 79,
    isNew: false,
  },
  {
    id: "hailuo-02",
    name: "Hailuo 02",
    company: "MiniMax",
    companyShort: "HM",
    type: "Видео",
    description: "Новый заметный видеогенератор для рекламных сцен, персонажей и motion-driven контента.",
    longDescription: "Набирающий популярность стек в сегменте text-to-video и image-to-video.",
    rating: 4.4,
    isFree: true,
    tags: ["Video", "Characters", "Trending"],
    accentFrom: "#00F2FF",
    accentTo: "#6E8BFF",
    heroBadge: "Rising Star",
    releaseNote: "Вошёл в обсуждение как сильный новый игрок видео-AI.",
    promptExample: "Сгенерируй неоновый пролёт по каталогу ИИ-моделей для launch-ролика.",
    strengths: ["Видеосцены", "Тренд", "Доступность"],
    bestFor: ["Эксперименты", "Креатив", "Контент"],
    pricingHint: "Обычно даёт стартовые бесплатные кредиты.",
    url: "https://www.minimaxi.com/",
    trendScore: 82,
    isNew: true,
  },
];

export const FEATURED_COMPARE_IDS = [
  "openai-gpt-4-5",
  "anthropic-claude-opus-4",
  "google-gemini-2-5-pro",
  "deepseek-r1",
];

export const QUICK_PROMPTS = [
  "Подбери мне лучшую нейросеть для кода",
  "Покажи топ моделей для генерации видео",
  "Какие модели можно попробовать бесплатно",
  "Сравни GPT-4.5 и Claude Opus 4",
  "Что выбрать для озвучки и голоса",
];
